### ISSUE TITLE
How to contact you

### ISSUE THREAD

**Issue by aerodolphin** [conradopoole/TwilightLord-ESP32-ETH-SHIELD-docs#1]
How I can contact you?

**Comment by conradopoole** [comment]
Hi @aerodolphin you can go to https://www.tindie.com/products/twilightlord/twilightlord-esp32-ethernet-shield/ , the is a "CONTACT SELLER" in the About Seller section.

<img width="377" alt="image" src="https://user-images.githubusercontent.com/5704796/154315924-82beedf5-2ecd-4903-bd1b-fe0d7050dee1.png">
